# Generated by Django 3.0.3 on 2020-10-15 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201014_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
