# Generated by Django 3.0.3 on 2020-10-15 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201015_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='interested_users',
            field=models.ManyToManyField(null=True, related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
