# Generated by Django 3.0.3 on 2020-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201015_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Art', 'Art'), ('Others', 'Others')], max_length=50)),
                ('listing', models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing')),
            ],
        ),
    ]
